### ISSUE TITLE
API Keys

### ISSUE THREAD

**Issue by SeaDude** [brentgarbe/Python_APIs#1]
Just a heads up, you have API keys stored in plain text in your Github repo. These could be abused by those with malintents. You might consider using a `.gitignore` file to refrain from uploading. 
Cheers man and thanks for posting your homework! It provided me some python study that aligns with what i'm learning at the moment.

**Comment by brentgarbe** [comment]
Thank you for the heads up! I will do that, I am glad that you were able to use this to better your understanding in Python. Happy coding
